# Generated by Django 3.2.14 on 2022-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='upwork',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='the_year',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='the_year',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
